import { ReadOnlyCatalog } from "../core/base/read-only-catalog.mjs";
import { UNIT_TOKENS } from "./unit-token-catalog.mjs";

const UNIT_SYMBOL_ENTRIES = Object.freeze({
  [UNIT_TOKENS.METER]: UNIT_TOKENS.METER,
  [UNIT_TOKENS.CENTIMETER]: UNIT_TOKENS.CENTIMETER,
  [UNIT_TOKENS.MILLIMETER]: UNIT_TOKENS.MILLIMETER,
  [UNIT_TOKENS.INCH]: UNIT_TOKENS.INCH,
  [UNIT_TOKENS.SQUARE_CENTIMETER]: "cm²",
  [UNIT_TOKENS.SQUARE_METER]: "m²",
  [UNIT_TOKENS.SQUARE_INCH]: "in²",
  [UNIT_TOKENS.CUBIC_CENTIMETER]: "cm³",
  [UNIT_TOKENS.CUBIC_METER]: "m³",
  [UNIT_TOKENS.CUBIC_INCH]: "in³",
  [UNIT_TOKENS.LITER]: "L",
  [UNIT_TOKENS.RADIAN]: UNIT_TOKENS.RADIAN,
  [UNIT_TOKENS.DEGREE]: "°",
  [UNIT_TOKENS.DEGREE_CELSIUS]: "°C",
  [UNIT_TOKENS.DEGREE_FAHRENHEIT]: "°F",
  [UNIT_TOKENS.KELVIN]: UNIT_TOKENS.KELVIN,
  [UNIT_TOKENS.KILOGRAM]: UNIT_TOKENS.KILOGRAM,
  [UNIT_TOKENS.NEWTON]: UNIT_TOKENS.NEWTON,
  [UNIT_TOKENS.KILONEWTON]: UNIT_TOKENS.KILONEWTON,
  [UNIT_TOKENS.PASCAL]: UNIT_TOKENS.PASCAL,
  [UNIT_TOKENS.KILOPASCAL]: UNIT_TOKENS.KILOPASCAL,
  [UNIT_TOKENS.MEGAPASCAL]: UNIT_TOKENS.MEGAPASCAL,
  [UNIT_TOKENS.BAR]: UNIT_TOKENS.BAR,
  [UNIT_TOKENS.SECOND]: UNIT_TOKENS.SECOND,
  [UNIT_TOKENS.MINUTE]: UNIT_TOKENS.MINUTE,
  [UNIT_TOKENS.HOUR]: UNIT_TOKENS.HOUR,
  [UNIT_TOKENS.PERCENT]: "%",
  [UNIT_TOKENS.UN]: UNIT_TOKENS.UN,
  [UNIT_TOKENS.BOOL]: UNIT_TOKENS.BOOL
});

export class UnitSymbolCatalog extends ReadOnlyCatalog {
  constructor() {
    super(UNIT_SYMBOL_ENTRIES);
  }
}

export const unitSymbolCatalog = new UnitSymbolCatalog();
export const UNIT_SYMBOLS = unitSymbolCatalog.all();