import { ReadOnlyCatalog } from "../core/base/read-only-catalog.mjs";
import { MATHJS_STRINGS } from "./mathjs-string-catalog.mjs";

const UNIT_SYMBOL_ENTRIES = Object.freeze({
  [MATHJS_STRINGS.METER]: MATHJS_STRINGS.METER,
  [MATHJS_STRINGS.CENTIMETER]: MATHJS_STRINGS.CENTIMETER,
  [MATHJS_STRINGS.MILLIMETER]: MATHJS_STRINGS.MILLIMETER,
  [MATHJS_STRINGS.INCH]: MATHJS_STRINGS.INCH,
  [MATHJS_STRINGS.SQUARE_CENTIMETER]: "cm²",
  [MATHJS_STRINGS.SQUARE_METER]: "m²",
  [MATHJS_STRINGS.SQUARE_INCH]: "in²",
  [MATHJS_STRINGS.CUBIC_CENTIMETER]: "cm³",
  [MATHJS_STRINGS.CUBIC_METER]: "m³",
  [MATHJS_STRINGS.CUBIC_INCH]: "in³",
  [MATHJS_STRINGS.LITER]: "L",
  [MATHJS_STRINGS.RADIAN]: MATHJS_STRINGS.RADIAN,
  [MATHJS_STRINGS.DEGREE]: "°",
  [MATHJS_STRINGS.DEGREE_CELSIUS]: "°C",
  [MATHJS_STRINGS.DEGREE_FAHRENHEIT]: "°F",
  [MATHJS_STRINGS.KELVIN]: MATHJS_STRINGS.KELVIN,
  [MATHJS_STRINGS.KILOGRAM]: MATHJS_STRINGS.KILOGRAM,
  [MATHJS_STRINGS.NEWTON]: MATHJS_STRINGS.NEWTON,
  [MATHJS_STRINGS.KILONEWTON]: MATHJS_STRINGS.KILONEWTON,
  [MATHJS_STRINGS.PASCAL]: MATHJS_STRINGS.PASCAL,
  [MATHJS_STRINGS.KILOPASCAL]: MATHJS_STRINGS.KILOPASCAL,
  [MATHJS_STRINGS.MEGAPASCAL]: MATHJS_STRINGS.MEGAPASCAL,
  [MATHJS_STRINGS.BAR]: MATHJS_STRINGS.BAR,
  [MATHJS_STRINGS.SECOND]: MATHJS_STRINGS.SECOND,
  [MATHJS_STRINGS.MINUTE]: MATHJS_STRINGS.MINUTE,
  [MATHJS_STRINGS.HOUR]: MATHJS_STRINGS.HOUR,
  [MATHJS_STRINGS.PERCENT]: "%"
});

export class UnitSymbolCatalog extends ReadOnlyCatalog {
  constructor() {
    super(UNIT_SYMBOL_ENTRIES);
  }
}

export const unitSymbolCatalog = new UnitSymbolCatalog();
export const UNIT_SYMBOLS = unitSymbolCatalog.all();