import { createPreset } from "./create-preset.mjs";
import { UNIT_TOKENS } from "../constants/unit-token-catalog.mjs";
import { OUTPUT_SUFFIX_MODES } from "../constants/output-suffix-modes.mjs";
import { QUANTITY_TYPES } from "../constants/quantity-types.mjs";

export const BOOL_PRESETS = Object.freeze({
  "bool:yes-no": createPreset({
    id: "bool:yes-no",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Yes / No",
    description: "Boolean display as Yes/No labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "YES_NO"
  }),
  "bool:active-inactive": createPreset({
    id: "bool:active-inactive",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Active / Inactive",
    description: "Boolean display as Active/Inactive labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "ACTIVE_INACTIVE"
  }),
  "bool:enabled-disabled": createPreset({
    id: "bool:enabled-disabled",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Enabled / Disabled",
    description: "Boolean display as Enabled/Disabled labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "ENABLED_DISABLED"
  }),
  "bool:included-excluded": createPreset({
    id: "bool:included-excluded",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Included / Excluded",
    description: "Boolean display as Included/Excluded labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "INCLUDED_EXCLUDED"
  }),
  "bool:valid-invalid": createPreset({
    id: "bool:valid-invalid",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Valid / Invalid",
    description: "Boolean display as Valid/Invalid labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "VALID_INVALID"
  }),
  "bool:compliant-noncompliant": createPreset({
    id: "bool:compliant-noncompliant",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Compliant / Non-compliant",
    description: "Boolean display as Compliant/Non-compliant labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "COMPLIANT_NON_COMPLIANT"
  }),
  "bool:locked-unlocked": createPreset({
    id: "bool:locked-unlocked",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Locked / Unlocked",
    description: "Boolean display as Locked/Unlocked labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "LOCKED_UNLOCKED"
  }),
  "bool:visible-hidden": createPreset({
    id: "bool:visible-hidden",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Visible / Hidden",
    description: "Boolean display as Visible/Hidden labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "VISIBLE_HIDDEN"
  }),
  "bool:open-closed": createPreset({
    id: "bool:open-closed",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Open / Closed",
    description: "Boolean display as Open/Closed labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "OPEN_CLOSED"
  }),
  "bool:reviewed-not-reviewed": createPreset({
    id: "bool:reviewed-not-reviewed",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Reviewed / Not reviewed",
    description: "Boolean display as Reviewed/Not reviewed labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "REVIEWED_NOT_REVIEWED"
  }),
  "bool:approved-not-approved": createPreset({
    id: "bool:approved-not-approved",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Approved / Not approved",
    description: "Boolean display as Approved/Not approved labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "APPROVED_NOT_APPROVED"
  }),
  "bool:required-not-required": createPreset({
    id: "bool:required-not-required",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Required / Not required",
    description: "Boolean display as Required/Not required labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "REQUIRED_NOT_REQUIRED"
  }),
  "bool:applicable-not-applicable": createPreset({
    id: "bool:applicable-not-applicable",
    quantity: QUANTITY_TYPES.BOOL,
    name: "Applicable / Not applicable",
    description: "Boolean display as Applicable/Not applicable labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "APPLICABLE_NOT_APPLICABLE"
  })
});
