import { createPreset } from "./create-preset.mjs";
import { UNIT_TOKENS } from "../constants/unit-token-catalog.mjs";
import { OUTPUT_SUFFIX_MODES } from "../constants/output-suffix-modes.mjs";
import { QUANTITY_TYPES } from "../constants/quantity-types.mjs";

export const NONE_PRESETS = Object.freeze({
  "none:count": createPreset({
    id: "none:count",
    quantity: QUANTITY_TYPES.NONE,
    name: "Unit Count",
    description: "Generic whole-number count with unit suffix for discrete items.",
    unit: UNIT_TOKENS.UN,
    precision: 0,
    showUnit: true,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.CODE
  }),
  "none:count-pcs": createPreset({
    id: "none:count-pcs",
    quantity: QUANTITY_TYPES.NONE,
    name: "Unit Count (pcs)",
    description: "Whole-number count with 'pcs' custom suffix for parts or components.",
    unit: UNIT_TOKENS.UN,
    precision: 0,
    showUnit: false,
    prefix: "Qty ",
    suffix: " pcs",
    suffixMode: OUTPUT_SUFFIX_MODES.CUSTOM
  }),
  "none:yes-no": createPreset({
    id: "none:yes-no",
    quantity: QUANTITY_TYPES.NONE,
    name: "Yes / No",
    description: "Boolean display as Yes/No labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "YES_NO"
  }),
  "none:active-inactive": createPreset({
    id: "none:active-inactive",
    quantity: QUANTITY_TYPES.NONE,
    name: "Active / Inactive",
    description: "Boolean display as Active/Inactive labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "ACTIVE_INACTIVE"
  }),
  "none:enabled-disabled": createPreset({
    id: "none:enabled-disabled",
    quantity: QUANTITY_TYPES.NONE,
    name: "Enabled / Disabled",
    description: "Boolean display as Enabled/Disabled labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "ENABLED_DISABLED"
  }),
  "none:included-excluded": createPreset({
    id: "none:included-excluded",
    quantity: QUANTITY_TYPES.NONE,
    name: "Included / Excluded",
    description: "Boolean display as Included/Excluded labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "INCLUDED_EXCLUDED"
  }),
  "none:valid-invalid": createPreset({
    id: "none:valid-invalid",
    quantity: QUANTITY_TYPES.NONE,
    name: "Valid / Invalid",
    description: "Boolean display as Valid/Invalid labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "VALID_INVALID"
  }),
  "none:compliant-noncompliant": createPreset({
    id: "none:compliant-noncompliant",
    quantity: QUANTITY_TYPES.NONE,
    name: "Compliant / Non-compliant",
    description: "Boolean display as Compliant/Non-compliant labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "COMPLIANT_NON_COMPLIANT"
  }),
  "none:locked-unlocked": createPreset({
    id: "none:locked-unlocked",
    quantity: QUANTITY_TYPES.NONE,
    name: "Locked / Unlocked",
    description: "Boolean display as Locked/Unlocked labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "LOCKED_UNLOCKED"
  }),
  "none:visible-hidden": createPreset({
    id: "none:visible-hidden",
    quantity: QUANTITY_TYPES.NONE,
    name: "Visible / Hidden",
    description: "Boolean display as Visible/Hidden labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "VISIBLE_HIDDEN"
  }),
  "none:open-closed": createPreset({
    id: "none:open-closed",
    quantity: QUANTITY_TYPES.NONE,
    name: "Open / Closed",
    description: "Boolean display as Open/Closed labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "OPEN_CLOSED"
  }),
  "none:reviewed-not-reviewed": createPreset({
    id: "none:reviewed-not-reviewed",
    quantity: QUANTITY_TYPES.NONE,
    name: "Reviewed / Not reviewed",
    description: "Boolean display as Reviewed/Not reviewed labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "REVIEWED_NOT_REVIEWED"
  }),
  "none:approved-not-approved": createPreset({
    id: "none:approved-not-approved",
    quantity: QUANTITY_TYPES.NONE,
    name: "Approved / Not approved",
    description: "Boolean display as Approved/Not approved labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "APPROVED_NOT_APPROVED"
  }),
  "none:required-not-required": createPreset({
    id: "none:required-not-required",
    quantity: QUANTITY_TYPES.NONE,
    name: "Required / Not required",
    description: "Boolean display as Required/Not required labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "REQUIRED_NOT_REQUIRED"
  }),
  "none:applicable-not-applicable": createPreset({
    id: "none:applicable-not-applicable",
    quantity: QUANTITY_TYPES.NONE,
    name: "Applicable / Not applicable",
    description: "Boolean display as Applicable/Not applicable labels with raw 0/1 editing.",
    unit: UNIT_TOKENS.BOOL,
    precision: 0,
    showUnit: false,
    prefix: "",
    suffix: "",
    suffixMode: OUTPUT_SUFFIX_MODES.NONE,
    booleanLabelKey: "APPLICABLE_NOT_APPLICABLE"
  })
});
